[versions]
paper = "1.21.11-R0.1-SNAPSHOT"
cloud = "2.1.0-SNAPSHOT"
cloudPaper = "2.0.0-SNAPSHOT"
coroutine = "1.10.2"
serialization = "1.9.0"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
betonquest = { group = "org.betonquest", name = "betonquest", version = "3.0.0-20250818.215240-364" }
mineauth-api = { group = "com.github.morinoparty.MineAuth", name = "api", version = "v0.2.24" }

kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }


cloud = { group = "org.incendo", name = "cloud-core", version.ref = "cloud" }
cloud-annotations = { group = "org.incendo", name = "cloud-annotations", version.ref = "cloud" }
cloud-kotlin-coroutines-annotations = { group = "org.incendo", name = "cloud-kotlin-coroutines-annotations", version.ref = "cloud" }
cloudPaper = { group = "org.incendo", name = "cloud-paper", version.ref = "cloudPaper" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.3.10" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "2.2.10" }
shadow = { id = "com.gradleup.shadow", version = "9.3.2-SNAPSHOT" }
run-paper = { id = "xyz.jpenilla.run-paper", version = "3.0.2" }
resource-factory = { id = "xyz.jpenilla.resource-factory", version = "1.3.1" }

[bundles]
commands = ["cloud", "cloudPaper", "cloud-annotations", "cloud-kotlin-coroutines-annotations"]
coroutines = ["kotlinx-coroutines-core"]
